name: CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      # Dar permisos de ejecución a jest
      - run: chmod +x node_modules/.bin/jest

      - run: npm test
